backfill_statistics:
  fields:
    start_date:
      required: true
      example: "2024-01-01"
      selector:
        date: {}
    end_date:
      required: false
      example: "2024-11-30"
      selector:
        date: {}
